# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/error.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'common/v1/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/v1/error.proto\x12\x0elemo.common.v1\"f\n\x0b\x45rrorDetail\x12\'\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x19.lemo.common.v1.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x66ield\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t*\xd0\x05\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n\x13\x45RROR_CODE_INTERNAL\x10\xe8\x07\x12 \n\x1b\x45RROR_CODE_INVALID_ARGUMENT\x10\xe9\x07\x12\x19\n\x14\x45RROR_CODE_NOT_FOUND\x10\xea\x07\x12\x1e\n\x19\x45RROR_CODE_ALREADY_EXISTS\x10\xeb\x07\x12!\n\x1c\x45RROR_CODE_PERMISSION_DENIED\x10\xec\x07\x12\x1f\n\x1a\x45RROR_CODE_UNAUTHENTICATED\x10\xed\x07\x12\"\n\x1d\x45RROR_CODE_RESOURCE_EXHAUSTED\x10\xee\x07\x12#\n\x1e\x45RROR_CODE_FAILED_PRECONDITION\x10\xef\x07\x12\x17\n\x12\x45RROR_CODE_ABORTED\x10\xf0\x07\x12\x1c\n\x17\x45RROR_CODE_OUT_OF_RANGE\x10\xf1\x07\x12\x1d\n\x18\x45RROR_CODE_UNIMPLEMENTED\x10\xf2\x07\x12\x1b\n\x16\x45RROR_CODE_UNAVAILABLE\x10\xf3\x07\x12!\n\x1c\x45RROR_CODE_DEADLINE_EXCEEDED\x10\xf4\x07\x12\"\n\x1d\x45RROR_CODE_SCENARIO_NOT_FOUND\x10\xd0\x0f\x12\x1e\n\x19\x45RROR_CODE_ITEM_NOT_FOUND\x10\xd1\x0f\x12$\n\x1f\x45RROR_CODE_EXPERIMENT_NOT_FOUND\x10\xd2\x0f\x12\x1f\n\x1a\x45RROR_CODE_MODEL_NOT_FOUND\x10\xd3\x0f\x12\'\n\"ERROR_CODE_INVALID_SCENARIO_CONFIG\x10\xda\x0f\x12\x1d\n\x18\x45RROR_CODE_RECALL_FAILED\x10\xe4\x0f\x12\x1b\n\x16\x45RROR_CODE_RANK_FAILED\x10\xe5\x0f\x12\x1d\n\x18\x45RROR_CODE_RERANK_FAILED\x10\xe6\x0f\x42GZEcodeup.aliyun.com/zls/lemo_go/andrew-protos/gen/go/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZEcodeup.aliyun.com/zls/lemo_go/andrew-protos/gen/go/common/v1;commonv1'
  _globals['_ERRORCODE']._serialized_start=146
  _globals['_ERRORCODE']._serialized_end=866
  _globals['_ERRORDETAIL']._serialized_start=41
  _globals['_ERRORDETAIL']._serialized_end=143
# @@protoc_insertion_point(module_scope)
