version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: lemo-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lemo_recommender
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lemo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # 注意：以下服务使用本地已有配置
  # ==========================================
  # Redis: localhost:6379 (密码: redis_password_2024)
  # Kafka: localhost:9092
  # Milvus: localhost:19530 (gRPC), localhost:9091 (HTTP)
  # MinIO: localhost:9000 (API), localhost:8001 (Console)
  # Etcd: localhost:2379
  # Attu (Milvus管理界面): localhost:8000

  # Prometheus (监控)
  prometheus:
    image: prom/prometheus:latest
    container_name: lemo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - lemo-network

  # Grafana (可视化)
  grafana:
    image: grafana/grafana:latest
    container_name: lemo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - lemo-network

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  lemo-network:
    driver: bridge

