# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommender_common/v1/common.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'recommender_common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"recommender_common/v1/common.proto\x12\x1alemo.recommender_common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"P\n\tSortField\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x34\n\x05order\x18\x02 \x01(\x0e\x32%.lemo.recommender_common.v1.SortOrder\"i\n\tTimeRange\x12.\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x92\x01\n\x08Metadata\x12.\n\ncreated_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x03 \x01(\t\x12\x12\n\nupdated_by\x18\x04 \x01(\t*P\n\tSortOrder\x12\x1a\n\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n\x0fSORT_ORDER_DESC\x10\x02*\\\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n\x0eSTATUS_DELETED\x10\x03\x42^Z\\codeup.aliyun.com/zls/lemo_go/andrew-protos/gen/go/recommender_common/v1;recommendercommonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender_common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\\codeup.aliyun.com/zls/lemo_go/andrew-protos/gen/go/recommender_common/v1;recommendercommonv1'
  _globals['_SORTORDER']._serialized_start=494
  _globals['_SORTORDER']._serialized_end=574
  _globals['_STATUS']._serialized_start=576
  _globals['_STATUS']._serialized_end=668
  _globals['_RESPONSE']._serialized_start=99
  _globals['_RESPONSE']._serialized_end=154
  _globals['_SORTFIELD']._serialized_start=156
  _globals['_SORTFIELD']._serialized_end=236
  _globals['_TIMERANGE']._serialized_start=238
  _globals['_TIMERANGE']._serialized_end=343
  _globals['_METADATA']._serialized_start=346
  _globals['_METADATA']._serialized_end=492
# @@protoc_insertion_point(module_scope)
