apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: lemo-recommender
  labels:
    app: recommendation-service
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
        version: v1
    spec:
      containers:
      - name: recommendation-service
        image: lemo-recommender/recommendation-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8004
          protocol: TCP
        
        env:
        - name: SERVICE_PORT
          value: "8004"
        
        # 从ConfigMap加载配置
        envFrom:
        - configMapRef:
            name: lemo-recommender-config
        - secretRef:
            name: lemo-recommender-secret
        
        # 健康检查
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8004
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # 资源限制
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        
        # 优雅关闭
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      
      # 容错配置
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

