# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recommender.v1 import item_pb2 as recommender_dot_v1_dot_item__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommender/v1/item_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemServiceStub(object):
    """物品管理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/CreateItem',
                request_serializer=recommender_dot_v1_dot_item__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.BatchCreateItems = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/BatchCreateItems',
                request_serializer=recommender_dot_v1_dot_item__pb2.BatchCreateItemsRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.BatchCreateItemsResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/GetItem',
                request_serializer=recommender_dot_v1_dot_item__pb2.GetItemRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/ListItems',
                request_serializer=recommender_dot_v1_dot_item__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.ListItemsResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/UpdateItem',
                request_serializer=recommender_dot_v1_dot_item__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/DeleteItem',
                request_serializer=recommender_dot_v1_dot_item__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.DeleteItemResponse.FromString,
                _registered_method=True)
        self.BatchDeleteItems = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/BatchDeleteItems',
                request_serializer=recommender_dot_v1_dot_item__pb2.BatchDeleteItemsRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.BatchDeleteItemsResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/lemo.recommender.v1.ItemService/SearchItems',
                request_serializer=recommender_dot_v1_dot_item__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_item__pb2.SearchItemsResponse.FromString,
                _registered_method=True)


class ItemServiceServicer(object):
    """物品管理服务
    """

    def CreateItem(self, request, context):
        """创建物品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCreateItems(self, request, context):
        """批量创建物品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """获取物品详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """查询物品列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """更新物品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """删除物品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDeleteItems(self, request, context):
        """批量删除物品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """搜索物品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.CreateItemRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.CreateItemResponse.SerializeToString,
            ),
            'BatchCreateItems': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCreateItems,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.BatchCreateItemsRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.BatchCreateItemsResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.GetItemRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.GetItemResponse.SerializeToString,
            ),
            'ListItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.ListItemsRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.ListItemsResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.UpdateItemRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.UpdateItemResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.DeleteItemRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.DeleteItemResponse.SerializeToString,
            ),
            'BatchDeleteItems': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchDeleteItems,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.BatchDeleteItemsRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.BatchDeleteItemsResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=recommender_dot_v1_dot_item__pb2.SearchItemsRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_item__pb2.SearchItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemo.recommender.v1.ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemo.recommender.v1.ItemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """物品管理服务
    """

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/CreateItem',
            recommender_dot_v1_dot_item__pb2.CreateItemRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCreateItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/BatchCreateItems',
            recommender_dot_v1_dot_item__pb2.BatchCreateItemsRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.BatchCreateItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/GetItem',
            recommender_dot_v1_dot_item__pb2.GetItemRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/ListItems',
            recommender_dot_v1_dot_item__pb2.ListItemsRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.ListItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/UpdateItem',
            recommender_dot_v1_dot_item__pb2.UpdateItemRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/DeleteItem',
            recommender_dot_v1_dot_item__pb2.DeleteItemRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.DeleteItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchDeleteItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/BatchDeleteItems',
            recommender_dot_v1_dot_item__pb2.BatchDeleteItemsRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.BatchDeleteItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.ItemService/SearchItems',
            recommender_dot_v1_dot_item__pb2.SearchItemsRequest.SerializeToString,
            recommender_dot_v1_dot_item__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
