# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recommender.v1 import recommendation_pb2 as recommender_dot_v1_dot_recommendation__pb2
from recommender_common.v1 import health_pb2 as recommender__common_dot_v1_dot_health__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommender/v1/recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub(object):
    """推荐服务 - v2.0微服务架构

    职责：
    1. BFF编排层 - 调用召回/精排/重排服务
    2. 统一推荐入口
    3. 缓存管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/lemo.recommender.v1.RecommendationService/GetRecommendations',
                request_serializer=recommender_dot_v1_dot_recommendation__pb2.GetRecommendationsRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lemo.recommender.v1.RecommendationService/HealthCheck',
                request_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """推荐服务 - v2.0微服务架构

    职责：
    1. BFF编排层 - 调用召回/精排/重排服务
    2. 统一推荐入口
    3. 缓存管理
    """

    def GetRecommendations(self, request, context):
        """获取推荐结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=recommender_dot_v1_dot_recommendation__pb2.GetRecommendationsRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemo.recommender.v1.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemo.recommender.v1.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """推荐服务 - v2.0微服务架构

    职责：
    1. BFF编排层 - 调用召回/精排/重排服务
    2. 统一推荐入口
    3. 缓存管理
    """

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RecommendationService/GetRecommendations',
            recommender_dot_v1_dot_recommendation__pb2.GetRecommendationsRequest.SerializeToString,
            recommender_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RecommendationService/HealthCheck',
            recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
            recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecallServiceStub(object):
    """========== 召回服务 ==========

    召回服务 - 多路召回策略
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MultiRecall = channel.unary_unary(
                '/lemo.recommender.v1.RecallService/MultiRecall',
                request_serializer=recommender_dot_v1_dot_recommendation__pb2.MultiRecallRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommendation__pb2.MultiRecallResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lemo.recommender.v1.RecallService/HealthCheck',
                request_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RecallServiceServicer(object):
    """========== 召回服务 ==========

    召回服务 - 多路召回策略
    """

    def MultiRecall(self, request, context):
        """多路召回
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecallServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MultiRecall': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiRecall,
                    request_deserializer=recommender_dot_v1_dot_recommendation__pb2.MultiRecallRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommendation__pb2.MultiRecallResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemo.recommender.v1.RecallService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemo.recommender.v1.RecallService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecallService(object):
    """========== 召回服务 ==========

    召回服务 - 多路召回策略
    """

    @staticmethod
    def MultiRecall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RecallService/MultiRecall',
            recommender_dot_v1_dot_recommendation__pb2.MultiRecallRequest.SerializeToString,
            recommender_dot_v1_dot_recommendation__pb2.MultiRecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RecallService/HealthCheck',
            recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
            recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RankingServiceStub(object):
    """========== 精排服务 ==========

    精排服务 - 模型推理排序
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rank = channel.unary_unary(
                '/lemo.recommender.v1.RankingService/Rank',
                request_serializer=recommender_dot_v1_dot_recommendation__pb2.RankRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommendation__pb2.RankResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lemo.recommender.v1.RankingService/HealthCheck',
                request_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RankingServiceServicer(object):
    """========== 精排服务 ==========

    精排服务 - 模型推理排序
    """

    def Rank(self, request, context):
        """对候选物品进行精排
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Rank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rank,
                    request_deserializer=recommender_dot_v1_dot_recommendation__pb2.RankRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommendation__pb2.RankResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemo.recommender.v1.RankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemo.recommender.v1.RankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RankingService(object):
    """========== 精排服务 ==========

    精排服务 - 模型推理排序
    """

    @staticmethod
    def Rank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RankingService/Rank',
            recommender_dot_v1_dot_recommendation__pb2.RankRequest.SerializeToString,
            recommender_dot_v1_dot_recommendation__pb2.RankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RankingService/HealthCheck',
            recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
            recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RerankingServiceStub(object):
    """========== 重排服务 ==========

    重排服务 - 多样性/新鲜度/业务规则
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rerank = channel.unary_unary(
                '/lemo.recommender.v1.RerankingService/Rerank',
                request_serializer=recommender_dot_v1_dot_recommendation__pb2.RerankRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommendation__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lemo.recommender.v1.RerankingService/HealthCheck',
                request_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RerankingServiceServicer(object):
    """========== 重排服务 ==========

    重排服务 - 多样性/新鲜度/业务规则
    """

    def Rerank(self, request, context):
        """对排序后的物品进行重排
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RerankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=recommender_dot_v1_dot_recommendation__pb2.RerankRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommendation__pb2.RerankResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemo.recommender.v1.RerankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemo.recommender.v1.RerankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RerankingService(object):
    """========== 重排服务 ==========

    重排服务 - 多样性/新鲜度/业务规则
    """

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RerankingService/Rerank',
            recommender_dot_v1_dot_recommendation__pb2.RerankRequest.SerializeToString,
            recommender_dot_v1_dot_recommendation__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.RerankingService/HealthCheck',
            recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
            recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
