# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recommender.v1 import user_pb2 as recommender_dot_v1_dot_user__pb2
from recommender_common.v1 import health_pb2 as recommender__common_dot_v1_dot_health__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommender/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """用户服务 - v2.0微服务架构

    职责：
    1. 用户画像查询
    2. 用户实时特征获取
    3. 用户偏好管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserProfile = channel.unary_unary(
                '/lemo.recommender.v1.UserService/GetUserProfile',
                request_serializer=recommender_dot_v1_dot_user__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_user__pb2.GetUserProfileResponse.FromString,
                _registered_method=True)
        self.BatchGetUserProfiles = channel.unary_unary(
                '/lemo.recommender.v1.UserService/BatchGetUserProfiles',
                request_serializer=recommender_dot_v1_dot_user__pb2.BatchGetUserProfilesRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_user__pb2.BatchGetUserProfilesResponse.FromString,
                _registered_method=True)
        self.UpdateUserProfile = channel.unary_unary(
                '/lemo.recommender.v1.UserService/UpdateUserProfile',
                request_serializer=recommender_dot_v1_dot_user__pb2.UpdateUserProfileRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_user__pb2.UpdateUserProfileResponse.FromString,
                _registered_method=True)
        self.GetUserRealtimeFeatures = channel.unary_unary(
                '/lemo.recommender.v1.UserService/GetUserRealtimeFeatures',
                request_serializer=recommender_dot_v1_dot_user__pb2.GetUserRealtimeFeaturesRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_user__pb2.GetUserRealtimeFeaturesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lemo.recommender.v1.UserService/HealthCheck',
                request_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """用户服务 - v2.0微服务架构

    职责：
    1. 用户画像查询
    2. 用户实时特征获取
    3. 用户偏好管理
    """

    def GetUserProfile(self, request, context):
        """获取用户画像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetUserProfiles(self, request, context):
        """批量获取用户画像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """更新用户画像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRealtimeFeatures(self, request, context):
        """获取用户实时特征
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=recommender_dot_v1_dot_user__pb2.GetUserProfileRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_user__pb2.GetUserProfileResponse.SerializeToString,
            ),
            'BatchGetUserProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetUserProfiles,
                    request_deserializer=recommender_dot_v1_dot_user__pb2.BatchGetUserProfilesRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_user__pb2.BatchGetUserProfilesResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=recommender_dot_v1_dot_user__pb2.UpdateUserProfileRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_user__pb2.UpdateUserProfileResponse.SerializeToString,
            ),
            'GetUserRealtimeFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRealtimeFeatures,
                    request_deserializer=recommender_dot_v1_dot_user__pb2.GetUserRealtimeFeaturesRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_user__pb2.GetUserRealtimeFeaturesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemo.recommender.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemo.recommender.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """用户服务 - v2.0微服务架构

    职责：
    1. 用户画像查询
    2. 用户实时特征获取
    3. 用户偏好管理
    """

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.UserService/GetUserProfile',
            recommender_dot_v1_dot_user__pb2.GetUserProfileRequest.SerializeToString,
            recommender_dot_v1_dot_user__pb2.GetUserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetUserProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.UserService/BatchGetUserProfiles',
            recommender_dot_v1_dot_user__pb2.BatchGetUserProfilesRequest.SerializeToString,
            recommender_dot_v1_dot_user__pb2.BatchGetUserProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.UserService/UpdateUserProfile',
            recommender_dot_v1_dot_user__pb2.UpdateUserProfileRequest.SerializeToString,
            recommender_dot_v1_dot_user__pb2.UpdateUserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserRealtimeFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.UserService/GetUserRealtimeFeatures',
            recommender_dot_v1_dot_user__pb2.GetUserRealtimeFeaturesRequest.SerializeToString,
            recommender_dot_v1_dot_user__pb2.GetUserRealtimeFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemo.recommender.v1.UserService/HealthCheck',
            recommender__common_dot_v1_dot_health__pb2.HealthCheckRequest.SerializeToString,
            recommender__common_dot_v1_dot_health__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
