apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: lemo-recommender
  labels:
    app: recommendation-service
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
  - name: http
    port: 8004
    targetPort: 8004
    protocol: TCP
  sessionAffinity: None

---
# Ingress配置（如果需要对外暴露）
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recommendation-service-ingress
  namespace: lemo-recommender
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: recommender.example.com
    http:
      paths:
      - path: /api/v1/recommend
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 8004
  tls:
  - hosts:
    - recommender.example.com
    secretName: recommender-tls-secret

