apiVersion: v1
kind: ConfigMap
metadata:
  name: lemo-service-recommender-config
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    environment: dev
data:
  # Application
  ENV: "prod"
  LOG_LEVEL: "INFO"
  
  # MongoDB (外网服务器)
  MONGODB_URL: "mongodb://lemo_user:lemo_password_2024@111.228.39.41:27017/lemo_recommender"
  MONGODB_DATABASE: "lemo_recommender"
  
  # Redis (外网服务器)
  REDIS_URL: "redis://:redis_password_2024@111.228.39.41:6379/0"
  
  # Celery (使用 Redis)
  CELERY_BROKER_URL: "redis://:redis_password_2024@111.228.39.41:6379/1"
  CELERY_RESULT_BACKEND: "redis://:redis_password_2024@111.228.39.41:6379/2"
  
  # Kafka (外网服务器)
  KAFKA_BOOTSTRAP_SERVERS: "111.228.39.41:9092"
  KAFKA_ITEM_INGEST_TOPICS: '["items-ingest","vlog-items","news-items"]'
  
  # Milvus (外网服务器)
  MILVUS_HOST: "111.228.39.41"
  MILVUS_PORT: "19530"
  
  # MinIO (外网服务器 - 如果需要)
  MINIO_ENDPOINT: "111.228.39.41:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  
  # Etcd (外网服务器 - 如果需要)
  ETCD_ENDPOINTS: "111.228.39.41:2379"
  
  # Prometheus
  PROMETHEUS_PORT: "9090"
  
  # API Server
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "10071"
  
  # gRPC Server
  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "10072"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemo-service-recommender-http
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    component: http
    environment: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lemo-service-recommender
      component: http
      environment: dev
  template:
    metadata:
      labels:
        app: lemo-service-recommender
        component: http
        environment: dev
    spec:
      serviceAccountName: lemo-service-recommender-sa
      imagePullSecrets:
      - name: regcred
      containers:
      - name: recommender-http
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["python3", "services/recommender/main_http.py"]
        ports:
        - containerPort: 10071
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: APP_ENV
          value: "prod"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: lemo-service-recommender-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 10071
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 10071
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemo-service-recommender-grpc
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    component: grpc
    environment: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lemo-service-recommender
      component: grpc
      environment: dev
  template:
    metadata:
      labels:
        app: lemo-service-recommender
        component: grpc
        environment: dev
        kratos-service-app: lemo-service-recommender
        kratos-service-id: recommender-001
        kratos-service-version: "1.0.0"
      annotations:
        kratos-service-metadata: '{"env":"dev"}'
        kratos-service-protocols: '{"10072":"grpc"}'
    spec:
      serviceAccountName: lemo-service-recommender-sa
      imagePullSecrets:
      - name: regcred
      containers:
      - name: recommender-grpc
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["python3", "services/recommender/main_grpc.py"]
        ports:
        - containerPort: 10072
          name: grpc
          protocol: TCP
        env:
        - name: APP_ENV
          value: "prod"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: lemo-service-recommender-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "python3 -c 'import grpc; channel = grpc.insecure_channel(\"localhost:10072\"); channel.close()'"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "python3 -c 'import grpc; channel = grpc.insecure_channel(\"localhost:10072\"); channel.close()'"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lemo-service-recommender-http
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    component: http
    environment: dev
spec:
  type: NodePort
  selector:
    app: lemo-service-recommender
    component: http
    environment: dev
  ports:
  - name: http
    port: 10071
    targetPort: 10071
    nodePort: 30801
  - name: metrics
    port: 9090
    targetPort: 9090
    nodePort: 30802
---
apiVersion: v1
kind: Service
metadata:
  name: lemo-service-recommender
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    component: grpc
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: lemo-service-recommender
    component: grpc
    environment: dev
  ports:
  - name: grpc
    port: 10072
    targetPort: 10072
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lemo-service-recommender-sa
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    environment: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lemo-service-recommender-role
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    environment: dev
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lemo-service-recommender-rolebinding
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    environment: dev
subjects:
- kind: ServiceAccount
  name: lemo-service-recommender-sa
  namespace: lemo-dev
roleRef:
  kind: Role
  name: lemo-service-recommender-role
  apiGroup: rbac.authorization.k8s.io

