apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemo-service-recommender-beat
  namespace: lemo-dev
  labels:
    app: lemo-service-recommender
    component: beat
    environment: dev
spec:
  replicas: 1  # Beat 只能1个副本！
  strategy:
    type: Recreate  # Beat 不支持滚动更新
  selector:
    matchLabels:
      app: lemo-service-recommender
      component: beat
      environment: dev
  template:
    metadata:
      labels:
        app: lemo-service-recommender
        component: beat
        environment: dev
    spec:
      serviceAccountName: lemo-service-recommender-sa
      imagePullSecrets:
      - name: regcred
      containers:
      - name: recommender-beat
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        # 使用 RedBeat 调度器（Redis 存储，K8s 友好）
        command: 
        - "celery"
        - "-A"
        - "app.tasks.celery_app"
        - "beat"
        - "-l"
        - "info"
        - "--scheduler"
        - "redbeat.RedBeatScheduler"
        env:
        - name: APP_ENV
          value: "prod"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CELERY_BROKER_URL
          value: "redis://:redis_password_2024@111.228.39.41:6379/1"
        - name: CELERY_RESULT_BACKEND
          value: "redis://:redis_password_2024@111.228.39.41:6379/2"
        envFrom:
        - configMapRef:
            name: lemo-service-recommender-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # 检查 Beat 进程是否存在
              if ! ps aux | grep -v grep | grep 'celery.*beat' > /dev/null; then
                exit 1
              fi
              # 检查 Redis 连接（Beat 依赖 Redis）
              python3 -c "import redis; r = redis.Redis.from_url('redis://:redis_password_2024@111.228.39.41:6379/1'); r.ping()" || exit 1
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # 检查进程和 Redis 连接
              ps aux | grep -v grep | grep 'celery.*beat' > /dev/null && \
              python3 -c "import redis; r = redis.Redis.from_url('redis://:redis_password_2024@111.228.39.41:6379/1'); r.ping()"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10

